# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180629_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
